notifications:
  email: false
  slack:
    rooms: typer2:lLH4I2CxXf7ZJpiuf3Blx79D
    on_success: always
    on_failure: always

dist: trusty
sudo: required
branches:
  only:
  - master
language: csharp
mono: none
dotnet: 1.0.0-preview2-003121
install: dotnet restore Backend/Test/$TEST_DIR
addons:
  sonarqube:
    token: 265ea5c180b88564c9c3bf8a18a73dbb598ef8ee
script:
  - dotnet test Backend/Test/$TEST_DIR
  - sonar-scanner
env:
  - TEST_DIR=ExampleService.Test
  - TEST_DIR=AuthService.Test
  - TEST_DIR=UserService.Test
  - TEST_DIR=OrderService.Test
  - TEST_DIR=PaymentService.Test
  - TEST_DIR=Orchestrator.Test
  - TEST_DIR=EmailService.Test
  - TEST_DIR=ProductService.Test
